### ISSUE TITLE
Missing sudo in "Dealing with Multiple Failed Nodes" in readthedocs 

### ISSUE THREAD

**Issue by jack-atack** [Metaswitch/project-clearwater-issues#27]
I've been following the **Dealing with Multiple Failed Nodes** section of the Project Clearwater [readthedocs](http://clearwater.readthedocs.io/en/stable/Handling_Multiple_Failed_Nodes.html?)

In the[ `Recreate the data store cluster values in etcd`](http://clearwater.readthedocs.io/en/stable/Handling_Multiple_Failed_Nodes.html?#recreate-the-data-store-cluster-values-in-etcd), the final command requires sudo permissions to run:

```
[vellum-1]ubuntu@node:/etc/clearwater$ /usr/share/clearwater/clearwater-cluster-manager/scripts/load_from_cassandra_cluster vellum
You must run this script with root permissions
```

**Comment by johadalin** [comment]
Fixed up :)
