### ISSUE TITLE
Wrong base image in Dockerfiles

### ISSUE THREAD

**Issue by chbndrhnns** [Metaswitch/project-clearwater-issues#28]
#### Symptoms
The instruction `FROM clearwater/base` seems to be incorrect. `docker-compose` fails with 

```
Building sprout
Step 1/9 : FROM clearwater/base
ERROR: Service 'sprout' failed to build: repository clearwater/base not found: does not exist or no pull access
```

#### Impact
Installation not possible

#### Steps to reproduce
Run `docker-compose`.

**Comment by johadalin** [comment]
Hi @chbndrhnns  
We build all of our component docker images from a base image, which sets up the repositories etc. From the looks of it, you haven't built the clearwater/base image before running docker compose. In the steps in the readme at https://github.com/Metaswitch/clearwater-docker/blob/master/README.md#using-compose , before running docker-compose, you need to install the dependencies and build the base image. Can you re-run the steps
```
# Build the base Clearwater docker image.
cd clearwater-docker
sudo docker build -t clearwater/base base
```
and double check that it successfully build the image?

**Comment by chbndrhnns** [comment]
you are right. This step was not completed before.

**Comment by johadalin** [comment]
Sorry we didn't get to looking at this for a while. Hopefully you were able to resolve this before hand on your own/use one of our other deployment methods :smile: 
You might find a quicker response on the Clearwater mailing list if you hit any more issues in the future. Check out http://www.projectclearwater.org/community/ for info on how to sign up  for it
